### ISSUE TITLE
File path not found

### ISSUE THREAD

**Issue by Jscott388** [Retsly/data-dictionary#19]
I am having file not found for my files. How do I get this to work?

**Comment by EnFinlay** [comment]
Hi @Jscott388, what are you trying to do / what command are you running?

**Comment by Jscott388** [comment]
Maybe I am using this for the wrong purpose? This creates the schema correct? The synonyms will match the incoming data fields? Cause the data I get from my MLS is stuff like LM_Char10_7 as the System Name, tons of field without Standard Names. I am never seen schemas created this way with mongoose. I have always done them the old fashion way. 

Before I was using something like this:

`LM_Char10_7: {
type: string,
alias: 'BasementDim'
}`

`
Syntax might be off, but this how I was saving my data. But since there is a data dictionary I wanted to use it for my schema. Yes I will have to go through and add all the fields to the matching data dictionary but this will keep it more simple to manage in the long run. 

So if I add L_ListingID to synonyms in ListingKey will that work? If not I could use this as a base and turn it into a alias since mongoose will match that. 

But back to the main question, I am not sure about setting the FILE environment path. I have used the full path to my file, Can't find file.

**Comment by lvivier** [comment]
Hi @Jscott388, this tool creates Mongoose-like schemas from the Excel version of the DD (which you have to download from https://www.reso.org/data-dictionary/). It does not do any mapping between an MLS's schema and the Data Dictionary as you show in your example.

The FILE environment variable is for pointing the [bin/all script](https://github.com/Retsly/data-dictionary/blob/master/bin/all) at the Data Dictionary Excel file when it is generating new schemas.

In our own toolset we have a transforming tool that converts between an MLS's own schema and Data Dictionary. We use the schemas in this repo to validate that the output of that tool is correct.

**Comment by Jscott388** [comment]
Oh ok. So I still need to make the mapping tool for the Rets data. This just handles the data dictionary only. Thanks!
